alias ll='ls -lFGa --color'
alias l='ls -lFGa --color'
alias h='history'
alias grepp='grep --color=auto -In --exclude-dir={.build,.git} --exclude={.tags,tags,cscope.out}'
alias ns='netstat -tulpn'

alias g='git'
alias gf='git fetch'
alias gs='git status'
alias gd='git diff'
alias gc='git commit'
alias gca='git commit -a'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gp='git push'
alias gl='git log --oneline'
alias gb='git batch'
alias gch='git checkout'
alias gcp='git cherry-pick'
alias gsui='git submodule update --init'
alias gsur='git submodule update --remote'

alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias .......='cd ../../../../../../'

alias vimrc='vim ~/.vimrc'
alias zshrc='vim ~/.zshrc'
alias loadzsh='source ~/.zshrc'
alias bashrc='vim ~/.bashrc'
alias loadbash='source ~/.bashrc'
alias sshrc='vim ~/.ssh/config'
alias tmuxrc='vim ~/.tmux.conf'
